### ISSUE TITLE
Evaluate token groups scope for better CLAIM

### ISSUE THREAD

**Issue by iaean** [dns3l/web#21]
User input should handled in a way the user can expect, that an operation is allowed and probably successful.
This is actually not the case with `auth` and `rtzn`.

It would be great to evaluate the groups scope of an user and reflect to usable root suffixes. Meaning:
```yaml
rtzn:
  - root: foo.example.net.
  - root: foo.example.org.
  - root: foo.example.io.
```
```json
"groups": [
  "[<prefix>]example.net",
  "[<prefix>]bar.example.org",
  "[<prefix>]bar.example.io" ]
```
resulting in `foo.example.net` choosable root zone only.

Support from https://github.com/dns3l/dns3l-core/issues/62 is highly appreciated.
